### ISSUE TITLE
希望能在按下Spacebar弹出页面的页脚处，展示torrent内含文件的总数与总大小

### ISSUE THREAD

**Issue by StealthField** [emako/QuickLook.Plugin.TorrentViewer#1]
like this
![03A98801B9DC3A91B8064DE6D50958FD](https://github.com/emako/QuickLook.Plugin.TorrentViewer/assets/106151305/160ca24c-baf7-46cd-8979-f369516de4a5)

> 顺带一提，https://github.com/QL-Win/QuickLook/wiki/Available-Plugins#list-of-plugins QL插件列表里您提交的末尾这个最新的[TorrentViewer](https://github.com/Cologler/QuickLook.Plugin.TorrentViewer) v1.0.0插件，对应链接跳转的是上一个torrent插件开发者的页面（不知道是否有误，后面的[Link](https://github.com/emako/QuickLook.Plugin.TorrentViewer/releases) Rlease链接是正确对应的您的页面）

**Comment by emako** [comment]
啊，原来有人做过了呀。

**Comment by emako** [comment]
https://github.com/QL-Win/QuickLook/wiki/Available-Plugins 的link错误已修复

**Comment by emako** [comment]
https://github.com/emako/QuickLook.Plugin.TorrentViewer/releases/tag/v1.0.3
